### ISSUE TITLE
Use non-blocking SQL lib

### ISSUE THREAD

**Issue by prryplatypus** [winnipegfir/with-you-bot#3]
MySQL connector is a blocking library, which means the event loop stops running while the input/output operation completes. Instead, an asynchronous library like [aiomysql](https://github.com/aio-libs/aiomysql) should be used. Same goes for HTTP requests if any are made: You should use `aiohttp` (which gets installed with the discord.py lib automagically).

**Comment by kolbyd** [comment]
Now using aiomysql with commit e73167c19ec5b8b364dcedb365819d1901be41d0. Thanks!
